#ifndef OPENTERA_WEBRTC_NATIVE_CLIENT_PYTHON_CONFIGURATIONS_VIDEO_SOURCE_CONFIGURATION_PYTHON_H
#define OPENTERA_WEBRTC_NATIVE_CLIENT_PYTHON_CONFIGURATIONS_VIDEO_SOURCE_CONFIGURATION_PYTHON_H

#include <pybind11/pybind11.h>

namespace opentera
{
    PYBIND11_EXPORT void initVideoSourceConfigurationPython(pybind11::module& m);
}

#endif
