# Get MacOS version tests
name: mac-get-version

on:
  workflow_dispatch:

jobs:
  version:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, macos-11, macos-12]

    steps:
      - name: Version from "/usr/bin/sw_vers"
        run: /usr/bin/sw_vers

      - name: Version from "uname -v"
        run: uname -v
