# Get MacOS version tests
name: mac-get-version

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  version:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, macos-11, macos-12]

    steps:
      - uses: actions/checkout@v2

      - name: Version from "sw_vers"
        run: sw_vers -productVersion

      - name: Parsed version from "sw_vers"
        run: sw_vers -productVersion | perl -pe 's/(\d+(?:\.\d+)?)\.\d+/$1/'

      - name: Version from CMake
        run: cmake -P macos_get_version.cmake
